disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "" 

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "January 2, 2006"
  description = ""
  copyright = "Â© 2026 tecknet.gg"

[params.author]
  name = "Jeevan Hatti"
  email = "hattijeevan@example.com"
  image = "images/default.png"
  imageQuality = 96
  headline = "tecknet.gg"
  bio = "-"
  links = [
    {discord = "https:discord.com/users/821413155208822816"}, { instagram = "https://instagram.com/tecknet.gg" }, {linkedin = "https://www.linkedin.com/in/jeevan-hatti-82a22a2b0/"}, {github = "https://github.com/tecknet-gg"}
  ]
